server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: 13257653246
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml


logging:
  level:
    com.chang.springsecurity.mapper: debug